defmodule Enverse.Repo.Migrations.AddRecordSpecialAttrs do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:records) do
      add :latitude, :float
      add :longitude, :float
      add :elevation, :float
      add :time, :utc_datetime
    end
  end

  def down do
    alter table(:records) do
      remove :time
      remove :elevation
      remove :longitude
      remove :latitude
    end
  end
end
