defmodule Enverse.Repo.Migrations.RemoveRecordPk do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:records) do
      remove :id
    end
  end

  def down do
    alter table(:records) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v4()"), primary_key: true
    end
  end
end
